### ISSUE TITLE
cmake gitignore

### ISSUE THREAD

**Issue by FannoFlow** [janklab/matlab-bench#5]
the cmake autogenerated files should be added to the gitignore

https://github.com/github/gitignore/blob/master/CMake.gitignore

**Comment by apjanke** [comment]
Since this is benchmarking code, I'm actually taking the unusual approach of checking all build artifacts into the repo, so people can examine the exact build I used, down to disassembling the code if they want. I should probably come up with a better directory structure for it, though.
